set_property PACKAGE_PIN P17 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]

## switch
set_property PACKAGE_PIN P5 [get_ports Input[7]]
set_property IOSTANDARD LVCMOS33 [get_ports Input[7]]
set_property PACKAGE_PIN P4 [get_ports Input[6]]
set_property IOSTANDARD LVCMOS33 [get_ports Input[6]]
set_property PACKAGE_PIN P3 [get_ports Input[5]]
set_property IOSTANDARD LVCMOS33 [get_ports Input[5]]
set_property PACKAGE_PIN P2 [get_ports Input[4]]
set_property IOSTANDARD LVCMOS33 [get_ports Input[4]]
set_property PACKAGE_PIN R2 [get_ports Input[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Input[3]]
set_property PACKAGE_PIN M4 [get_ports Input[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Input[2]]
set_property PACKAGE_PIN N4 [get_ports Input[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Input[1]]
set_property PACKAGE_PIN R1 [get_ports Input[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Input[0]]

set_property SEVERITY {Warning} [get_drc_checks LUTLP-1] 
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

set_property PACKAGE_PIN B4 [get_ports Figure1[6]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure1[6]]
set_property PACKAGE_PIN A4 [get_ports Figure1[5]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure1[5]]
set_property PACKAGE_PIN A3 [get_ports Figure1[4]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure1[4]]
set_property PACKAGE_PIN B1 [get_ports Figure1[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure1[3]]
set_property PACKAGE_PIN A1 [get_ports Figure1[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure1[2]]
set_property PACKAGE_PIN B3 [get_ports Figure1[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure1[1]]
set_property PACKAGE_PIN B2 [get_ports Figure1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure1[0]]
set_property PACKAGE_PIN D4 [get_ports Figure2[6]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure2[6]]
set_property PACKAGE_PIN E3 [get_ports Figure2[5]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure2[5]]
set_property PACKAGE_PIN D3 [get_ports Figure2[4]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure2[4]]
set_property PACKAGE_PIN F4 [get_ports Figure2[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure2[3]]
set_property PACKAGE_PIN F3 [get_ports Figure2[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure2[2]]
set_property PACKAGE_PIN E2 [get_ports Figure2[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure2[1]]
set_property PACKAGE_PIN D2 [get_ports Figure2[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Figure2[0]]
set_property PACKAGE_PIN G2 [get_ports DN0[0]]
set_property IOSTANDARD LVCMOS33 [get_ports DN0[0]]
set_property PACKAGE_PIN C2 [get_ports DN0[1]]
set_property IOSTANDARD LVCMOS33 [get_ports DN0[1]]
set_property PACKAGE_PIN C1 [get_ports DN0[2]]
set_property IOSTANDARD LVCMOS33 [get_ports DN0[2]]
set_property PACKAGE_PIN H1 [get_ports DN0[3]]
set_property IOSTANDARD LVCMOS33 [get_ports DN0[3]]
set_property PACKAGE_PIN G1 [get_ports DN1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports DN1[0]]
set_property PACKAGE_PIN F1 [get_ports DN1[1]]
set_property IOSTANDARD LVCMOS33 [get_ports DN1[1]]
set_property PACKAGE_PIN E1 [get_ports DN1[2]]
set_property IOSTANDARD LVCMOS33 [get_ports DN1[2]]
set_property PACKAGE_PIN G6 [get_ports DN1[3]]
set_property IOSTANDARD LVCMOS33 [get_ports DN1[3]]

set_property PACKAGE_PIN V1 [get_ports LockButton]
set_property IOSTANDARD LVCMOS33 [get_ports LockButton]
set_property PACKAGE_PIN R11 [get_ports ChangeButton]
set_property IOSTANDARD LVCMOS33 [get_ports ChangeButton]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets LockButton]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ChangeButton]

set_property PACKAGE_PIN K3 [get_ports Alarm_Out]
set_property IOSTANDARD LVCMOS33 [get_ports Alarm_Out]

set_property PACKAGE_PIN H6 [get_ports Status1]
set_property IOSTANDARD LVCMOS33 [get_ports Status1]
set_property PACKAGE_PIN H5 [get_ports Status2]
set_property IOSTANDARD LVCMOS33 [get_ports Status2]